site_name: Auto-GPT
site_url: https://docs.agpt.co/
repo_url: https://github.com/Significant-Gravitas/Auto-GPT
nav:
  - 首页: index.md
  - 安装: setup.md
  - 用法: usage.md
  - 插件: plugins.md
  - 架构:
      - 代理: architecture/agents.md
      - 插件: architecture/plugins.md
  - 配置:
      - 选项: configuration/options.md
      - 搜索: configuration/search.md
      - 记忆: configuration/memory.md
      - 消息队列: configuration/message_queue.md
      - 语音: configuration/voice.md
      - 图像生成: configuration/imagegen.md

  - 帮助我们改进 Auto-GPT:
      - 分享调试日志: share-your-logs.md
      - 贡献指南: contributing.md
      - 运行测试: testing.md
      - 行为准则: code-of-conduct.md

  - 挑战:
      - 简介: challenges/introduction.md
      - 挑战列表:
          - 记忆:
              - 简介: challenges/memory/introduction.md
              - 记忆挑战 A: challenges/memory/challenge_a.md
              - 记忆挑战 B: challenges/memory/challenge_b.md
              - 记忆挑战 C: challenges/memory/challenge_c.md
              - 记忆挑战 D: challenges/memory/challenge_d.md
          - 信息检索:
              - 简介: challenges/information_retrieval/introduction.md
              - 信息检索挑战 A: challenges/information_retrieval/challenge_a.md
              - 信息检索挑战 B: challenges/information_retrieval/challenge_b.md
  - 提交挑战: challenges/submit.md
  - 解决挑战: challenges/beat.md

  - 许可证: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/LICENSE

theme:
  name: material
  icon:
    logo: material/book-open-variant
  favicon: imgs/Auto_GPT_Logo.png
  features:
    - navigation.sections
    - toc.follow
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - table-reader
  - search

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _javascript/tablesort.js
  - _javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
