"""Generate plugin modules from .spec.json files.

This script reads JSON spec files under ``plugins/stubs`` and writes
Python modules to ``plugins/<name>.py``. If an OpenAI API key is
available, it will request code from the API. Otherwise it will create
a basic stub implementation.
"""

from __future__ import annotations

import os
from pathlib import Path
import json

from black import FileMode, format_str
from autogpt.plugins.loader import load_plugin_meta

try:
    from openai import OpenAI
    openai_client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
except Exception:  # pragma: no cover - optional
    openai_client = None


AUTO_HEADER = "# AUTO-GENERATED BY generate_plugins.py. DO NOT EDIT\n"


def llm_generate(spec: dict) -> str:
    """Generate plugin code either via OpenAI or fallback."""
    if openai_client:
        messages = [
            {
                "role": "system",
                "content": (
                    "You generate Python plugin modules based on a JSON spec. "
                    "Return only valid Python code."
                ),
            },
            {"role": "user", "content": json.dumps(spec)},
        ]
        response = openai_client.chat.completions.create(
            model=os.environ.get("OPENAI_MODEL", "gpt-3.5-turbo"),
            messages=messages,
            temperature=0,
        )
        return response.choices[0].message.content
    # Fallback simple code
    func_name = spec.get("name", "plugin_function")
    description = spec.get("description", "")
    return f'def {func_name}(x):\n    """{description}"""\n    return x\n'


def generate_plugins(base_dir: Path | str = Path(__file__).resolve().parents[1]):
    base = Path(base_dir)
    stubs_dir = base / "plugins" / "stubs"
    out_dir = base / "plugins"
    out_dir.mkdir(exist_ok=True)
    for spec_file in stubs_dir.glob("*.spec.json"):
        spec = load_plugin_meta(spec_file)
        name = spec.name or spec_file.stem
        code = llm_generate(spec.dict())
        formatted = format_str(AUTO_HEADER + "\n" + code, mode=FileMode())
        target = out_dir / f"{name}.py"
        with open(target, "w", encoding="utf-8") as f:
            f.write(formatted)
        print(f"Generated {target}")


if __name__ == "__main__":  # pragma: no cover
    generate_plugins()
